helm repo add grafana https://grafana.github.io/helm-charts &&
  helm repo update &&
  helm upgrade --install --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring \
    --version "^4" --namespace "default" --create-namespace --values - <<'EOF'
cluster:
  name: ozgurvm2-cluster
destinations:
  grafana-cloud-metrics:
    type: prometheus
    url: https://prometheus-prod-58-prod-eu-central-0.grafana.net./api/prom/push
    auth:
      type: basic
      username: "3099622"
      password: ${GRAFANA_TOKEN}
  grafana-cloud-logs:
    type: loki
    url: https://logs-prod-039.grafana.net./loki/api/v1/push
    auth:
      type: basic
      username: "1545486"
      password: ${GRAFANA_TOKEN}
  gc-otlp-endpoint:
    type: otlp
    url: https://otlp-gateway-prod-eu-central-0.grafana.net./otlp
    protocol: http
    auth:
      type: basic
      username: "1587697"
      password: ${GRAFANA_TOKEN}
    metrics:
      enabled: true
    logs:
      enabled: true
    traces:
      enabled: true
  grafana-cloud-profiles:
    type: pyroscope
    url: https://profiles-prod-024.grafana.net.:443
    auth:
      type: basic
      username: "1587697"
      password: ${GRAFANA_TOKEN}
clusterMetrics:
  enabled: true
  collector: alloy-metrics
hostMetrics:
  enabled: true
  collector: alloy-metrics
  linuxHosts:
    enabled: true
  windowsHosts:
    enabled: false
  energyMetrics:
    enabled: true
costMetrics:
  enabled: true
  collector: alloy-metrics
clusterEvents:
  enabled: true
  collector: alloy-singleton
podLogsViaLoki:
  enabled: true
  collector: alloy-logs
applicationObservability:
  enabled: true
  collector: alloy-receiver
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
autoInstrumentation:
  enabled: true
  collector: alloy-metrics
  beyla:
    deliverTracesToApplicationObservability: false
profiling:
  enabled: true
  collector: alloy-profiles
collectors:
  alloy-metrics:
    presets:
      - clustered
      - statefulset
  alloy-singleton:
    presets:
      - singleton
  alloy-logs:
    presets:
      - filesystem-log-reader
      - daemonset
  alloy-receiver:
    presets:
      - deployment
  alloy-profiles:
    presets:
      - privileged
      - daemonset
collectorCommon:
  alloy:
    remoteConfig:
      enabled: true
      url: https://fleet-management-prod-024.grafana.net
      auth:
        type: basic
        username: "1587697"
        password: ${GRAFANA_TOKEN}
telemetryServices:
  kube-state-metrics:
    deploy: true
  node-exporter:
    deploy: true
  windows-exporter:
    deploy: false
  opencost:
    deploy: true
    metricsSource: grafana-cloud-metrics
    opencost:
      exporter:
        defaultClusterId: ozgurvm2-cluster
      prometheus:
        existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
        external:
          url: https://prometheus-prod-58-prod-eu-central-0.grafana.net./api/prom
  kepler:
    deploy: true
EOF