apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-database-secret-rule
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-auth-secret # CNPG'nin kullanacağı hedef şifre
  data:
  - secretKey: username
    remoteRef:
      key: secret/prod/database/postgres
      property: user
  - secretKey: password
    remoteRef:
      key: secret/prod/database/postgres
      property: password